<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-22T07:54:54 CDT" name="Default suite" finished-at="2022-04-22T07:55:05 CDT" duration-ms="11143">
    <groups>
    </groups>
    <test started-at="2022-04-22T07:54:54 CDT" name="Default test" finished-at="2022-04-22T07:55:05 CDT" duration-ms="11143">
      <class name="demoBlaze.Users.TS001_DemoBlaze_Users_SignUp">
        <test-method is-config="true" signature="setUp()[pri:0, instance:demoBlaze.Users.TS001_DemoBlaze_Users_SignUp@59662a0b]" started-at="2022-04-22T07:54:54 CDT" name="setUp" finished-at="2022-04-22T07:54:56 CDT" duration-ms="2113" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="confiureMethod()[pri:0, instance:demoBlaze.Users.TS001_DemoBlaze_Users_SignUp@59662a0b]" started-at="2022-04-22T07:54:56 CDT" name="confiureMethod" finished-at="2022-04-22T07:55:02 CDT" duration-ms="5438" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confiureMethod -->
        <test-method signature="testCase001SignUp()[pri:0, instance:demoBlaze.Users.TS001_DemoBlaze_Users_SignUp@59662a0b]" started-at="2022-04-22T07:55:02 CDT" name="testCase001SignUp" description="TC001_DemoBlaze_Users_SignUp" finished-at="2022-04-22T07:55:05 CDT" duration-ms="3233" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at demoBlaze.Utilities.TS011_DemoBlaze_Utilities_ValidateAlertTxt.validateAlertText(TS011_DemoBlaze_Utilities_ValidateAlertTxt.java:17)
at demoBlaze.Users.TS001_DemoBlaze_Users_SignUp.testCase001SignUp(TS001_DemoBlaze_Users_SignUp.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase001SignUp -->
        <test-method is-config="true" signature="tearDownMethod()[pri:0, instance:demoBlaze.Users.TS001_DemoBlaze_Users_SignUp@59662a0b]" started-at="2022-04-22T07:55:05 CDT" name="tearDownMethod" finished-at="2022-04-22T07:55:05 CDT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownMethod -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:demoBlaze.Users.TS001_DemoBlaze_Users_SignUp@59662a0b]" started-at="2022-04-22T07:55:05 CDT" name="tearDown" finished-at="2022-04-22T07:55:05 CDT" duration-ms="308" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- demoBlaze.Users.TS001_DemoBlaze_Users_SignUp -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
